### PR TITLE
Updated ace-editor to v1.4.3

### PR DESCRIPTION
**Pull request by mashedkeyboard**
Very simple change, just updates ace to the latest version.

### CODE REVIEW

**Comment by codykrieger** [comment]
Thanks @mashedkeyboard. Please also run `update.sh` in the root of the repo to pull in the updated assets.

**Comment by mashedkeyboard** [comment]
All done! :)

**Comment by codykrieger** [comment]
👌 Thanks!

**Comment by codykrieger** [comment]
(Released on RubyGems as v4.2.)

**Pull request merged**
